### ISSUE TITLE
Video display is "backwards"

### ISSUE THREAD

**Issue by caboteria** [Affectiva/affdexme-osx#1]
The other AffdexMe implementations act like mirrors, i.e., if you move your head to the left, it also moves to the left in the screen.  This implementation is the opposite so when you move your head to one side, on the screen it moves to the other side.

**Comment by Affdex** [comment]
Yep, on the list of improvements.

Merçi.

Boisy Pitre | Mobile Visionary
(781) 996-3037 x201 | Affectiva | affdex.com <http://www.affdex.com/>

 <https://www.facebook.com/Affectiva>  <https://twitter.com/Affectiva>  <http://www.affdex.com/buzz/blog/>  <https://www.linkedin.com/company/affectiva_2>  <https://plus.google.com/115885368219797754125/posts>  <https://www.youtube.com/user/affectiva>

**Comment by stephen-phillips-affectiva** [comment]
This issue is fixed in version 3.2.0.  The Preferences dialog now includes a checkbox to flip the image horizontally.  Observed performance may be slightly slower when the image is flipped horizontally.
